server:
  port: 8080
mysql:
  host: localhost
  port: 3306
  username: root
  password: root1234
  dbname: myproject
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_name: "./stogares/logs/dev.001.log"
  max_size: 10
  max_backups: 5
  max_age: 30
  compress: true
