server:
  port: 8080
database:
  - user: admin
    password: admin
    host: localhost
    dbName: admin
  - user: SNet
    password: SNet
    host: localhost
    dbName: SNet
security:
  jwt:
    key: abc123